git:
  depth: 9999999

sudo: required

language: go

go:
  - 1.9.x

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

script:
  - script/ci/test/docker-run

after_script:
  - script/ci/genauthors

after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
  - script/ci/can-release && script/ci/release

env:
  global:
    - "PATH=$HOME/gopath/bin:$PATH"
    - secure: C3BckSzQvkFdxYwbA5djs2VhpaocJjeBT0zhCjLwNBhEazzet/Jw+Kb3OZ7g/r0t+P6+dScQpUMCWNjSC4YPL9dh6WqXZikGBsePGyD4/vLmpM1AyCrf8jkt3gV9boq6xUe82uus7GGSo1QwbvrEetYZbkWnmRLF1mQpY+9Qa+LsXhfXdQOih5+YzrcXcj32czrc3taUS4KfOk0WI3Q3g6vx4LaUrngir10DIiprpANS6hNZKFLxtaX/horkhxwtwD1u/Z6FHn+4zzCPVjfGjGH3Gstsy7FrOXUVTnhAkrcLjHhbFC9ovOqTkX1OXQLD3GPL7gbCk2dtmT7dLaCt+LFQGClxsR9rCF4bTq+4Ai3/0ltZ+FdNH42meM/WssA4wMRnoanezBSYiDSwe7X87LbSaAA+7TvB677prj1IE9a/0n/sphyQWgFb2VrF+FmV8u7eXUxFjjndjVn8YaqcqtMamCcEkWQ79ylLeRwmC7bksBIrielfHrbWpLI8CyQ/g8aVvQiTOzjKesTq+nX/5SGrqesMrWOOfz9kLFun/4YGc7xsviMhqzO8E0vdNgewM58Yi447H7vPnHAWxcqKYNxfMM6lnWrks1AzlDk3nFhO717YKZbDUaCmqQ9rWLkE8qeRD9f+53M95G+Eex+SGHUQuEi9tp/1O5/ixLm4hzs=
    - secure: uuJi/Dhw1gMYwyl5JCgq8axYhuA3dfkxl5J/dUa0L+SjtYTzfJjrUWHxmqku5EVnEJNq+jZPzWoefuo7dCWZWmCwW+D9aFavpG6lbGGG0U5Qt5dRlN7//SuiKhKdwQ6kPWzk2MF+xuYk7zYrsf04qTOPd/bE34AiM70U1iBax/wyZv262Yz5J3gpogEF9UjQweigBqVueMfKTzl+nI5wRICIK2HiKJoIDAhApJAVI6eYo2TiRocXpt5pZv8unslaBlgVV6HfLlYu1Vrq6vN3yAkDBZ8Vo4E3KdepKxT+G6GnrCWHpPg+sPOQWQv1yKG74onHM1a1MeRv20mF73W4qIykE+oovnnGGoW+B17xf1c6s3DZJzrWKhsTq72wsCD5KUPE2799yc+da7mYGC/Q+weAxKUeCDda4KGQhl5MmfMrDjKeveMhfriGwLsxT3bgbWxnZEEl6mcd18H1f9fa6Unbm97SZsPq4VAg2KSaZHEsJH+r2q2Mm+q5jPByOoZotLZiW0AFigG+kAvt5rSeDOx/NdqPAIVDazVhHQkIjzNlPkzimnPZ8Rkih3LqYz4U+rvQ8ZRz3S/Jo+at/ZRzUiQH7RKCZmHlXUpyvb0tF8fINLPdLg7fUlK5RMRMt+PzJPOr75u48GdbuF9RxULc9ucdq+NWbnAJLpD5x9Mv3MQ=

notifications:
  slack:
    secure: rAGArR9a8rX0oYoIcI64W0UbKPywQMrrHgRvY5YQQjHLaaQ/+wqDVxxHbsYnj6sterVkgP9oxFi2DDS5WL/EhNPqnUh5gAgFc33C3fY8oSC50f6ZTjzuIPLVYhCcCwdm2hbu/WBiNnnO3AqVjTcXL0L9PEn72UeEOyz9E+pWhQ+DVB5vRFQtT2bLqcXq0wXG2jXalsZVf+uJoJI1BPXPEn9y/r7jJcZd7ll0HyPZv474gArL2nmuLu9uXq8ek22D7lc9IYryJN/xoXw3wMbk5pVFjo3ypDZQtrbETOC+bO1ONkeVdW4mz1Z7O8XLK8nwx4lXHdCpRo0jfRgZehC0BgUBpz6y1cYm+eDj/R/xS9NwikKxovAwKmJhogS+iKMD7PKZ01xG84tBrGfXb05XTasP4vARWcB/+aMJXNrv9jUUw/ABOetTPa3k0r7utiVrvOBhu/dPgtCjdUDreEUmcGhsfdQgiObqy83YKJtW3qWFYdoGppW8WNlR/2D6mpWtny9H28N95/rLm2xi8PL9FUdXTCnts0KlvEYJOUSd+uCYVlE1T/GxM7jEcL4/tkRj8pbqT1qcblBrOUHgJ5EhL5UVM3z/ItpTL0dDL+K5VIm2fl6eTtR+8CYrNnUaMA+LglyAxGp85lcCrXTT1XmWgM7JFVhDjwOsIxPn0kx5bIQ=
